package bankAccounts.enums;

public enum ControllerResponseType {
    ERROR_CREATE_CHECKING_FIRST,
    SUCCESSFUL,
    INVALID_DEPOSIT_VALUE,
    UNKNOWN_ERROR,
    ACCOUNT_NOT_FOUND,
    INVALID_WITHDRAW_VALUE,
    NO_WITHDRAW_IN_MATURATION,
    DAILY_LIMIT_EXCEEDED,
    CUSTOMER_NOT_FOUND,
    CUSTOMER_EXIST,
    CHECKING_FINISHED
}
